features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
container_width: ''
header_width: header_width_contained
main_width: main_width_contained
footer_width: footer_width_contained
slider_show: 0
slider_speed: ''
slider_image: {  }
slider_code: ''
header_style: null
header_main_default: 0
header_main_padding_top: ''
header_main_padding_bottom: ''
header_page_default: 0
header_page_padding_top: ''
header_page_padding_bottom: ''
header_page_content_position: flex-start
front_sidebar: 0
sidebar_width_default: 0
sidebar_width_left: ''
sidebar_width_right: ''
sidebar_block_default: 0
sidebar_padding: ''
sidebar_radius: ''
sidebar_margin: ''
sidebar_title_font_size: ''
sidebar_title_transform: none
rtl: 0
node_author_pic: 0
node_tags: 0
footer_style: null
copyright_text: 0
comment_user_pic: 0
highlight_author_comment: 0
body_font_size: ''
body_line_height: ''
paragraph_bottom: ''
headings_default: 0
h1_size: ''
h1_weight: '400'
h1_transform: none
h1_height: ''
h2_size: ''
h2_weight: '400'
h2_transform: none
h2_height: ''
h3_size: ''
h3_weight: '400'
h3_transform: none
h3_height: ''
h4_size: ''
h4_weight: '400'
h4_transform: none
h4_height: ''
h5_size: ''
h5_weight: '400'
h5_transform: none
h5_height: ''
h6_size: ''
h6_weight: '400'
h6_transform: none
h6_height: ''
logo_default: 0
site_name_size: ''
site_name_weight: '400'
site_name_transform: none
site_name_height: ''
slogan_size: ''
slogan_transform: none
slogan_height: ''
slogan_style: normal
main_menu_default: 0
main_menu_top_size: ''
main_menu_top_weight: '400'
main_menu_top_transform: none
main_menu_sub_size: ''
main_menu_sub_weight: '400'
main_menu_sub_transform: none
page_title_default: 0
page_title_size_desktop: ''
page_title_size_mobile: ''
page_title_transform: none
breadcrumb_icon_style: null
button_default: 0
button_padding: ''
button_radius: ''
font_src: local
all_icons_show: 0
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: ''
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: ''
vimeo_url: ''
telegram_url: ''
whatsapp_url: ''
github_url: 'https://github.com/'
vk_url: ''
fontawesome_four: 0
fontawesome_five: 0
bootstrapicons: 0
scrolltotop_on: 0
scrolltotop_default: 0
scrolltotop_icon_style: null
scrolltotop_icon_size: ''
scrolltotop_icon_radius: ''
scrolltotop_position: null
scrolltotop_bottom: ''
styling: 0
styling_code: ''
