_core:
  default_config_hash: _0b2Dyb993JzkbRlFnYz7hMynhBxgPtAERPG2BDTudI
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: ''
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: ''
vimeo_url: ''
telegram_url: ''
whatsapp_url: ''
github_url: 'https://github.com/'
vk_url: ''
circle_type: circle_border
slider_show: 1
slider_code: ''
slider_image: {  }
slider_image_path: ''
front_sidebar: 1
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
font_icon_fontawesome: 0
font_icon_material: 0
copyright_text: 1
scrolltotop_on: 1
styling: 1
styling_code: ".cookiesjsr-settings {\r\n    display: none !important;\r\n}\r\n.cookiesjsr-banner {\r\n    background-color: #0d0f16 !important;\r\n}\r\n.cookiesjsr-btn {\r\n    color: black !important;\r\n}"
font_icon_fontawesome5: 0
