<?php

use \Drupal\node\NodeInterface;
use \Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render
 *
 * @param \Drupal\views\ViewExecutable $view
 * @return void
 */
function blog_vues_views_pre_render(ViewExecutable $view) {

    // Exclure l'actualité courante de la vue "A lire aussi"
    if ($view->id() == 'a_lire_aussi' && $view->current_display == 'block_1') {

        $node = \Drupal::routeMatch()->getParameter('node');
        if ($node instanceof NodeInterface) {
            $nid = $node->id();

            foreach ($view->result as $key => $value) {

                if ($value->nid == $nid) {
                    unset ($view->result[$key]);
                    break;
                }
            }
        }
    }
}

function blog_vues_node_view(array &$build, NodeInterface $node, $display, $view_mode) {
    $type = $node->getType();
    
    if ($type == 'actualite' || $type == 'recette') {
      $build['#cache']['max-age'] = 0;
    }
}

function blog_vues_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
    if ($route_match && $node = $route_match->getParameter('node')) {
      $breadcrumb->addCacheableDependency($node);
    }
}